services:
  - type: web
    name: naman-home-tutors
    runtime: python
    rootDir: tutoring_marketplace
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_ENV
        value: production
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
